### ISSUE TITLE
Suggestion: Use "real" Slash Commands

### ISSUE THREAD

**Issue by WorldMaker** [tznkai/CapersBot#3]
Discord now supports a / command API that offers some niceties as a user. It autocompletes as you type. It doesn't show up as a chat message. Discord offers help descriptions and argument information as you use them. Discord lets you clarify that you want a specific Bot when multiple bots offer commands with the same name.

Slash commands require webhooks (and so they need a hosting platform) and additional server permissions, so it makes sense not to start with them early in testing, and they can be harder to build/work with, but they can be a differentiator to making a bot feel more "professional" and as a user it is a nicer in-Discord experience without needing to jump to a manual site or fiddle around in a #bot-test channel with "help" commands.

https://discord.com/developers/docs/interactions/application-commands

**Comment by tznkai** [comment]
Updated it only to discover that Heroku has shut down its free hosting.
